language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.1
  - android-29
  - extra-android-m2repository
notifications:
  email: false
script:
- "./gradlew build"
- "./gradlew clean"
before_install:
- openssl aes-256-cbc -K $encrypted_adfbf0f992a7_key -iv $encrypted_adfbf0f992a7_iv
  -in apikey.properties.enc -out apikey.properties -d
