language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.1
    - android-29
    - extra-android-m2repository

notifications:
  email: false

script:
  - ./gradlew build
  - ./gradlew clean
# - ./gradlew build connectedCheck
#  - ./gradlew assemble check
#  - ./gradlew checkstyle
#  - ./gradlew build